main/urls.py
from django.urls import path, re_path
from django.conf.urls import include

from . import views

app_name='main'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/',views.register,name='register'),
    #path('login/',views.login,name='login'),
    #path('logout/',views.logout,name='logout'),
    path('prelim/<prelim_id>/',views.prelim_view,name='prelim_view'),
    path('soln/<soln_id>/vote/<val>',views.vote_view,name="vote_view"),
    path('problem/<prob_id>/',views.prob_view,name="prob_view"),
    #re_path(r'^browse/(?P<browseparam>.*)',views.search,name='search'),
    re_path(r'^browse/',views.search,name='search'),
    path('about/',views.about,name="about"),
    path('soln/community/<prob_id>/',views.community_soln,name="community_soln"),
    path('soln/community/<prob_id>/edit',views.edit_soln,name="edit_soln")
]

prelim/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from main.views import massTagView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',include('main.urls')),
    path('admin/prelim/masstag/',massTagView)
    
]
#TODO:
#visit this to register  /accounts/register/
#the rendered template is registration/registration_form.html

main/models.py
from django.db import models

from vote.models import VoteModel
from taggit.managers import TaggableManager
from simple_history.models import HistoricalRecords


# Create your models here.
class Prelim(models.Model):
    ID=models.AutoField(primary_key=True)
    year=models.IntegerField()
    season=models.IntegerField()
    abrev=models.CharField(max_length=6,null=True)


class Question(models.Model):
    ID=models.AutoField(primary_key=True)
    prelim=models.ForeignKey(Prelim,on_delete=models.CASCADE)
    Subject=models.IntegerField()
    number=models.IntegerField()
    default=models.CharField(max_length=20)
    tags=TaggableManager()
    long_form=models.CharField(max_length=10)

    
class Solution(VoteModel,models.Model):
    ID=models.AutoField(primary_key=True)
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    soln_ref=models.URLField()
    name=models.CharField(max_length=100)
#    score=models.FloatField(default=0.5)

class CommunitySolution(models.Model):
    ID=models.AutoField(primary_key=True)
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    soln_text=models.TextField()
    history=HistoricalRecords()
    changed_by=models.ForeignKey('auth.User',on_delete=models.SET_NULL,null=True)

    @property
    def _history_user(self):
        return self.changed_by

    @_history_user.setter
    def history_user(self,value):
        self.changed_by=value

main/forms.py
from django import forms
from .models import Question

import bleach

from ._form_aid import reverse_qid

class tagForm(forms.Form):
    tag_text=forms.CharField(label='add tags',max_length=100)

class editForm(forms.Form):
    comm_text=forms.CharField(widget=forms.Textarea)

class massTag(forms.Form):
    tag_field=forms.CharField()
    prob_field=forms.CharField()
    
    def save(self,commit=True):
        tag_txt=bleach.clean(self.cleaned_data.get('tag_field',None))
        p_txt=bleach.clean(self.cleaned_data.get('prob_field',None))
        tags=tag_txt.split(',')
        #format : J98M1
        for pf in p_txt.split(','):
            qid=reverse_qid(pf.replace(' ',''))
            prob=Question.objects.get(pk=qid)
            prob.tags.add(*tags)
      

main/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse
from django.contrib.admin.views.decorators import staff_member_required

from .forms import tagForm,editForm,massTag

from .models import Prelim,Question,Solution,CommunitySolution
from taggit.models import Tag

import bleach
from main._form_aid import convert_to_mathjax
# Create your views here.

prelim_num=35

def index(request):
    test_list=[Prelim.objects.get(pk=i) for i in range(35) ]
    test_list.reverse()
    q_and_tags=lambda x: [x,x.tags.all()]
    test_q_list=[[test, map(q_and_tags,test.question_set.all())] for test in test_list]
    
    context={
        'tests':test_q_list
    }
    return render(request,'main/index.html',context)

def about(request):
    return render(request,'main/about.html')


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            #user.save()
            login(request, user)
            return redirect('main:index')
    else:
        form = UserCreationForm()
    return render(request, 'main/register.html', {'form': form})

def prelim_view(request,prelim_id):
    head=get_object_or_404(Prelim,pk=prelim_id)
    questions=head.question_set.all()
    q_an_l=[[q,q.solution_set.all(),q.communitysolution_set.all()] for q in questions]

    nextn=head.ID+1
    if nextn>34:
        nextn=None
    prevn=head.ID-1
    if prevn<0:
        prevn=None
    context={
        'head':head,
        'solns':q_an_l,
        'nextn':nextn,
        'prevn':prevn,
    }
    return render(request,'main/prelim.html',context)

def vote_view(request,soln_id,val):
     soln=get_object_or_404(Solution,pk=soln_id)
     host_q=Question.objects.get(pk=soln.question.ID)
     host_p=Prelim.objects.get(pk=host_q.prelim.ID)

     if int(val)==0:
         soln.votes.up(request.user.id)
     else:
         soln.votes.down(request.user.id)

     return redirect('main:prelim_view',prelim_id=host_p.ID)
     
def prob_view(request,prob_id):
    prob=get_object_or_404(Question,pk=prob_id)
    
    if request.method == 'POST':
        if request.user.is_authenticated:
            form = tagForm(request.POST)
            if form.is_valid():
                #prob.tags.add(*form.value.split(' '))
                #print(form.value.split(' '))
                ftxt=form.cleaned_data.get('tag_text')
                #uhhhh maybe fix this??
                prob.tags.add(*ftxt.split(','))
        else:
            form=tagForm()
    else:
        form=tagForm()

    pdflink=None
    lnfm=prob.long_form
    #test=Prelim.objects.get(pk=prob.prelim)
    test=prob.prelim
    if lnfm[:4]!='2013' or test.season!=1:
        testn=lnfm[:4]+['J','M'][test.season]
        linkname=testn+lnfm[-1]+lnfm[-2]+'.pdf'
        pdflink='/static/main/q_pdfs/'+testn+'/'+linkname
        
    solns=prob.solution_set.all()
    tags=prob.tags.all()
    comm_soln=prob.communitysolution_set.all()

    
    pid=int(prob_id)-1
    if pid<0:
        pid=None
    nid=int(prob_id)+1
    if nid>419:
        nid=None
    
    context={
        'prob':prob,
        'solns':solns,
        'tags':tags,
        'form':form,
        'pdflink':pdflink,
        'comm_soln':comm_soln,
        'pid':pid,
        'nid':nid,
    }
    return render(request,'main/question.html',context)

def search(request):
    qset=Question.objects.none()
    searches=request.GET.get("question-search","").split(' ')
    for sf in searches:
        tset=Tag.objects.filter(slug__icontains=sf)
        for t in tset:
            qset=qset|Question.objects.filter(tags__name__in=[t])
    context={
        'questions':qset.distinct()
    }
    return render(request,'main/browse.html',context)


def community_soln(request,prob_id):
    prob=get_object_or_404(Question,pk=prob_id)
    soln=prob.communitysolution_set.first()
    context={
        'soln':soln,
    }
    return render(request,'main/community.html',context)

def edit_soln(request,prob_id):
    if request.user.is_authenticated:
        prob=get_object_or_404(Question,pk=prob_id)
        soln=prob.communitysolution_set.first()
        if request.method == 'POST':
            form=editForm(request.POST)
            if form.is_valid():
                ftxt=bleach.clean(form.cleaned_data.get('comm_text'))
                ftxt=convert_to_mathjax(ftxt)
                if not soln:
                    soln=CommunitySolution.objects.create(soln_text=ftxt,question=prob,changed_by=request.user)
                else:
                    soln.soln_text=ftxt
                    soln.changed_by=request.user
                
                soln.save()
            return redirect('main:community_soln',prob_id=prob_id)
        else:
            if soln:
                form=editForm(initial={'comm_text':soln.soln_text})
            else:
                form=editForm()
            context={
                'soln':soln,
                'form':form,
            }
            return render(request,'main/edit_comm.html',context)
    else:
        return redirect('main:community_soln',prob_id=prob_id)



@staff_member_required
def massTagView(request):

    if request.method=='POST':
        form=massTag(request.POST)
        if form.is_valid():
            form.save()

    form=massTag()
    context={
        'form':form
    }
    return render(request,'admin/massTag.html',context)

    

main/templates/main/about.html
{% extends "main/base.html"%}

{% block title%} About {% endblock %}

{% block content %}

<p style="margin:1em 0 3em 0 ;">
  This site is studying aid for the Princeton physics prelim. Originally this site was based off of the <a href="http://princetonprelims.wikidot.com/">the prelim wiki</a>, however it has been expanded to provide additional features. Currently the three primary features are the ability to rate the existing solutions on the prelim wiki based off of their accuracy, and searching the database of questions by topic. This is made possible by registered users adding tags and in a large part by Lysander's classification of the problems. Lastly you can upload Latex solutions. Which will then be editable by everyone else. The latex is rendered using <a href="http://docs.mathjax.org/en/latest/start.html#putting-mathematics-in-a-web-page">mathjax</a>, so you will have to use slightly different syntax as explained on the mathjax website. 
</p>
<p>
If you have any comments or feedback please let me know.
</p>


{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% load bootstrap3 %}
    {% bootstrap_css %}

    {% block header%}
    {% endblock %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'main/appstyle.css' %}" />
    <title>{% block title %}Princeton Prelims{% endblock %}</title>
</head>

<body>
  <div class="container-fluid">
    <nav class="navbar navbar-default pre_nav_style">
      <div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-1">
	  <a href="{% url 'main:index' %}">Prelims</a>
	</div>
	<div class="col-md-2">
	  <a href="{% url 'main:about' %}">About</a>
	</div>
	<div class="col-md-4"></div>
	<div class="col-md-2">

          <form action="/browse/" method="get" >
            {# csrf_token #}
            <input type="text" name="question-search" placeholder="Search..">
            <input type="submit" value="Search" />
          </form>

	</div>
	<div class="col-md-2">
	  {% if request.user.is_authenticated %}
	  <a href="{% url 'logout' %}?next=/">Logout</a>
	  {% else %}
	  <a href="{% url 'login' %}">Login</a>
	  <a href="{% url 'main:register' %}">Register</a>
	  {% endif %}
	</div>
      </div>
      
    </nav>
  </div>
  
  <div class="container-fluid">
    <div class="col-md-1"></div>
    <div class="col-md-10">
    {% block content%}
    {% endblock %}
    </div>
    <div class="col-md-1"></div>
  </div>
</body>

main/templates/main/browse.html
{% extends "main/base.html" %}

{% block title%}Princeton Prelims {% endblock %}

{% block content%}

{% if questions %}


<div class="row">
  {% for question in questions %}
  <div class="col-sm-1">
    <a href="{% url 'main:prob_view' question.ID%}">{{question.long_form}}</a>

    {% if forloop.counter|divisibleby:10 %}
    <div class="w-100"></div>
    {% endif %}
  </div>
  {% endfor %}
</div>

{% else %}
<div class="col-md-4"></div>
<div class="col-md-4">
  <p>
    No questions found with this tag.
  </p>
</div>
<div class="col-md-4"></div>
{% endif %}

{% endblock %}

main/templates/main/community.html
{% extends "main/base.html"%}

{% block title %}Community Solution {% endblock %}

{% block header %}
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script>
{%  endblock %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <h3>Solution to {{soln.question.long_form}}</h3>
  </div>
</div>

<div class="row">
  <div class="col-sm-2">
    <a href="{% url 'main:prob_view' soln.question.ID %}">Up</a>
  </div>
  <div class="col-sm-10">
    {% if user.is_authenticated %}
    <a href="{% url 'main:edit_soln' soln.question.ID%}">Edit</a>
    {% endif %}
  </div>
</div>

<div class="col-sm-12 community-soln" >
  {{soln.soln_text}}
</div>

{% endblock %}

main/templates/main/edit_comm.html
{% extends "main/base.html" %}

{% block title %}Edit Solution {% endblock %}

{% block content %}

<div class="row">

</div>

<div class="row">
  <form method="post">
    {% csrf_token %}
    
    {{form}}
    <button type="submit">Save Edit</button>
  </form>
</div>

{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %}

{% block title%}Princeton Prelims {% endblock %}

{% block content%}

    {% for test in tests %}
	<div class="row full-height {% cycle 'q-row-l' 'q-row-d' %}">
	    <div class="col-md-1 col-xs-1 ">
		<div class="row-start">
		    <a href="{% url 'main:prelim_view' test.0.ID%}">{{test.0.abrev}}</a>
		</div>
	    </div>
	    <div class="col-md-11 col-xs-11 ">
		<div class="flex-container">
		    {% for question  in test.1 %}
			<div  class="col-md-1 col-xs-2">
			    <a href="{% url 'main:prob_view' question.0.ID %}">
				{{question.0.default}}
			    </a>
			    <div  class="tag">
				{{question.1.0}}
			    </div>
			</div>
		    {% endfor %}
		</div>
	    </div>
	</div>
    {% endfor %}


{% endblock %}

main/templates/main/prelim.html
{% extends "main/base.html" %}


{% block title %} {{head.abrev}} {% endblock %}

{% block content %}

    <div class="row" style="margin:0 0 2em 0;">
	<div class="col-md-1">
	    <h3>{{head.abrev}}</h3>
	</div>
	<div class="col-md-1">
	    <a href="{% url 'main:index' %}">Up</a>
	</div>
	<div class="col-md-1">
	    {% if prevn %}
		<a href="{% url 'main:prelim_view' prevn %}">Previous</a>
	    {% endif %}
	</div>
	<div class="col-md-1">
	    {% if nextn %}
		<a href="{% url 'main:prelim_view' nextn %}">Next</a>
	    {% endif %}
	</div>
	
    </div>

    <div  style="display:flex;flex-direction:row;flex-wrap:wrap;">
	{% for qpair in solns %}
	    <div class="col-md-1 col-xs-4" >
		<div class="question-default">
		    <a href="{% url 'main:prob_view' qpair.0.ID %}">{{qpair.0.default}}</a>
		</div>
		<div class="soln-cell">
		    {% if qpair.2 %}
			<a href="{% url 'main:community_soln' qpair.0.ID%}">
			    Community Solution
			</a>
		    {% else %}
			{% if user.is_authenticated %}
			    <a href="{% url 'main:edit_soln' qpair.0.ID %}">
				Make Solution
			    </a>
			{% endif%}
		    {% endif %}
		</div>
		
		{% for soln in qpair.1%}
		    {% include "main/soln-cell.html" %}
		{% endfor %}
	    </div>
	{% endfor %}
    </div>

{% endblock %}

main/templates/main/question.html
{% extends "main/base.html" %}

{% block title %}{{prob.default}} {% endblock %}

{% block content %}

    <div class="row">
	<div class="col-md-3"></div>

	<div class="col-md-3 col-xs-6">
	    <h2>{{prob.long_form}}</h2>
	    <div class="row">
		<a href="{% url 'main:prelim_view' prob.prelim.ID %}">Up</a>&nbsp;
		{% if pid %}
		    <a href="{% url 'main:prob_view' pid %}">Previous</a>&nbsp;
		{% endif %}
		{% if nid %}
		    <a href="{% url 'main:prob_view' nid %}">Next</a>
		{% endif %}
	    </div>
	    {% if pdflink %}
		<a href="{{pdflink}}">pdf</a>
	    {% endif %}
	    <p>
		
		<b>Tags:</b>
		{% for tag in tags %}
		    {{tag}}{% if not forloop.last %},{% endif %}
		{% endfor %}
	    </p>
	    {% if request.user.is_authenticated %}
		<form method="post">
		    {% csrf_token %}
		    {{form.as_p}}
		    <button type="submit">Add</button>
		</form>
	    {% endif %}
	</div>
	<div class="col-md-4 col-xs-6">
	    <div  class="soln-cell">
		{% if comm_soln %}
		    <a href="{% url 'main:community_soln' prob.ID%}">Community Solution</a>
		{% else %}
		    {% if user.is_authenticated %}
			<a href="{% url 'main:edit_soln' prob.ID %}">Make Solution</a>
		    {% endif%}
		{% endif %}
	    </div>
	    {% for soln in solns%}
		{% include "main/soln-cell.html" %}
	    {% endfor %}
	</div>  
    </div>


    <div class="col-md-2"></div>

{% endblock %}

main/templates/main/register.html
{% extends "main/base.html" %}

{% block title%} Register  {% endblock %}

{% block content %}
<div class="col-md-4"></div>
<div class="col-md-4">
  <h2> Register </h2>

  <form method="post">
    {% csrf_token %}
    {% for field in form %}
    <p>
      {{field.label_tag}}<br>
      {{field}}
      {% for error in field.errors %}
    <p style="color:red;"> {{error}} </p>
    {% endfor %}
    </p>
    {% endfor %}
    <button type="submit">Register</button>
  </form>  
</div>
<div class="col-md-4"></div>
{% endblock %}

main/templates/main/soln-cell.html
{% load static %}
<div class="soln-cell" >
    <a href="{{soln.soln_ref}}">{{soln.name}}</a><br>
    <div  style="display:flex;align-items:center;">
	{% if request.user.is_authenticated %}
	    <div  style="display:flex;flex-direction:column;padding-right:.5em;">
		<a href="{% url 'main:vote_view' soln.ID 0 %}">
		    <img src="{% static 'main/up.png' %}" />
		</a>
		<a href="{% url 'main:vote_view' soln.ID 1 %}">
		    <img src="{% static 'main/down.png' %}" />
		</a>
	    </div>

	{% endif %}
	u:{{soln.num_vote_up}}/d:{{soln.num_vote_down}}
    </div>    
</div>